### ISSUE TITLE
New ways to import fonts

### ISSUE THREAD

**Issue by wit03** [roong-aroon-developer/RA-Event#1]
Please find new ways to import font (maybe locally download the IBM Plex Sans Thai file) and add it to our project because the current import is too big
![image](https://user-images.githubusercontent.com/40893632/97679007-47c77480-1ac7-11eb-97ab-7cef0d510d2a.png)

**Comment by someoneisyes** [comment]
🔨 Fixed by importing from hosted server. [https://lazywasabi.gitbook.io/cdn/fonts/ibm-plex-sans-thai](url)
